version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  ruby-send:
    image: send
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
  
  ruby-recieve:
    image: recieve
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
